version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: bookstore-postgres
    environment:
      POSTGRES_DB: bookstoredb
      POSTGRES_USER: bookstore
      POSTGRES_PASSWORD: bookstore
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bookstore-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookstore"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: bookstore-app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bookstoredb
      SPRING_DATASOURCE_USERNAME: bookstore
      SPRING_DATASOURCE_PASSWORD: bookstore
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - bookstore-network

volumes:
  postgres-data:

networks:
  bookstore-network:
    driver: bridge 